baseurl: "http://localhost/"
title: "Simon webdev"

contentdir:   "hugo/content"
dataDir:      "hugo/data"
assetDir:     "hugo/assets"
layoutdir:    "hugo/layouts"
themesdir:    "hugo/themes"
archetypedir: "hugo/archetype"
destination:  "public"
publishdir:   "public"
staticdir:    "static"

metaDataFormat: "yaml"
uglyURLs: false

disableSitemap: false
enableEmoji: true